#index:
#    path: /
#    controller: App\Controller\DefaultController::index

politiqueconfidential:
  path: /politique-confidentialite
  controller: App\Controller\DefaultController::politiqueconfidential