#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accueil:
  path: /accueil
  controller: App\Controller\DefaultController::accueil

concept:
  path: /letsmeatconcept
  controller: App\Controller\DefaultController::concept

proporeserv:
  path: /proposerreserver
  controller: App\Controller\DefaultController::proporeserv

profil:
  path: /profil
  controller: App\Controller\DefaultController::profil

amis:
  path: /retrouveramis
  controller: App\Controller\DefaultController::amis

contact:
  path: /contact
  controller: App\Controller\DefaultController::contact