#index:
#    path: /
#    controller: App\Controller\DefaultController::index

politiqueconfidential:
  path: /politique-confidentialite
  controller: App\Controller\DefaultController::politiqueconfidential

concept:
  path: /concept
  controller: App\Controller\DefaultController::concept

contact:
  path: /contact
  controller: App\Controller\DefaultController::contact

cgu:
  path: /cgu
  controller: App\Controller\DefaultController::cgu