#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accueil:
  path: /accueil
  controller: App\Controller\DefaultController::accueil

letsmeat_concept:
  path: /letsmeat_concept
  controller: App\Controller\DefaultController::letsmeat_concept

proposerreserver:
  path: /proposerreserver
  controller: App\Controller\DefaultController::proposerreserver

profil:
  path: /profil
  controller: App\Controller\DefaultController::profil

retrouveramiss:
  path: /retrouveramiss
  controller: App\Controller\DefaultController::retrouveramiss

contact:
  path: /contact
  controller: App\Controller\DefaultController::contact